services:
  - type: web
    name: hotel-queue-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PUBLIC_URL
        sync: false
      - key: DATA_DIR
        value: /var/data
